apiVersion: v1
kind: Service
metadata:
  name: dubbo-docker
  labels:
    run: dubbo
spec:
  type: NodePort
  ports:
    - port: 20880
      targetPort: 20880
      nodePort: 30001
  selector:
    run: dubbo-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-docker
spec:
  selector:
    matchLabels:
      run: dubbo
  replicas: 1
  template:
    metadata:
      labels:
        run: dubbo
    spec:
      containers:
        - name: dubbo-docker
          image: zouchengli/dubbo-demo
          env:
            - name: DUBBO_IP_TO_REGISTRY
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DUBBO_PORT_TO_REGISTRY
              value: "30001"
          tty: true
          ports:
            - containerPort: 20880